version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/suzhenghui/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: suzhenghui
    ports:
      - '3306:3306'
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/suzhenghui/redis:/data
    ports:
      - '6379:6379'
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
