POST http://localhost:3000/user/login
Content-Type: application/json
# Authorization: Bearer your_token

{
  "username": "lisi",
  "password": "333333"
}

POST http://localhost:3000/user/admin/update_password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoibGlzaSIsInJvbGVzIjpbIuaZrumAmueUqOaItyJdLCJwZXJtaXNzaW9ucyI6W3siaWQiOjEsImNvZGUiOiJjY2MiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBjY2Mg5o6l5Y-jIn1dLCJpYXQiOjE3NDQ0NzUwMjMsImV4cCI6MTc0NDQ3NjgyM30.0dpZxRrOmep69msT-D6Kgf9gFAYXkELYAJXWAjRYKnQ

{
  "password": "333333",
  "email": "yy@yy.com",
  "captcha": "123123"
}

POST http://localhost:3000/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoibGlzaSIsInJvbGVzIjpbIuaZrumAmueUqOaItyJdLCJwZXJtaXNzaW9ucyI6W3siaWQiOjEsImNvZGUiOiJjY2MiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBjY2Mg5o6l5Y-jIn1dLCJpYXQiOjE3NDQ0NzUwMjMsImV4cCI6MTc0NDQ3NjgyM30.0dpZxRrOmep69msT-D6Kgf9gFAYXkELYAJXWAjRYKnQ

{
  "nickName": "李思",
  "email": "yy@yy.com",
  "captcha": "123456",
  "headPic": "xxx.png"
}

GET http://localhost:3000/aaa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoibGlzaSIsInJvbGVzIjpbIuaZrumAmueUqOaItyJdLCJwZXJtaXNzaW9ucyI6W3siaWQiOjEsImNvZGUiOiJjY2MiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBjY2Mg5o6l5Y-jIn1dLCJpYXQiOjE3NDQ0NTkzODcsImV4cCI6MTc0NDQ2MTE4N30.pa3PsKE5pBcpR-k0vCqcP7ylzmR9_3vTejsJePow1ME


GET http://localhost:3000/user/refresh?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0NDQ1ODMwMSwiZXhwIjoxNzQ1MDYzMTAxfQ.i-hQ83hcQ7a1n1VB6IPLXo2aP759oCSWPr07wzOHZSo



POST http://localhost:3000/user/admin/login
Content-Type: application/json
# Authorization: Bearer your_token

{
  "username": "zhangsan",
  "password": "222222"
}

GET http://localhost:3000/aaa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiemhhbmdzYW4iLCJyb2xlcyI6WyLnrqHnkIblkZgiXSwicGVybWlzc2lvbnMiOlt7ImlkIjoxLCJjb2RlIjoiY2NjIiwiZGVzY3JpcHRpb24iOiLorr_pl64gY2NjIOaOpeWPoyJ9LHsiaWQiOjIsImNvZGUiOiJkZGQiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBkZGQg5o6l5Y-jIn1dLCJpYXQiOjE3NDQ0NzM5MjIsImV4cCI6MTc0NDQ3NTcyMn0.ufzn0XyK1T5svP5oU3NOuTfvdjvBf3dJ1BzLerASFiQ

GET http://localhost:3000/user/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiemhhbmdzYW4iLCJyb2xlcyI6WyLnrqHnkIblkZgiXSwicGVybWlzc2lvbnMiOlt7ImlkIjoxLCJjb2RlIjoiY2NjIiwiZGVzY3JpcHRpb24iOiLorr_pl64gY2NjIOaOpeWPoyJ9LHsiaWQiOjIsImNvZGUiOiJkZGQiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBkZGQg5o6l5Y-jIn1dLCJpYXQiOjE3NDQ0NzM5MjIsImV4cCI6MTc0NDQ3NTcyMn0.ufzn0XyK1T5svP5oU3NOuTfvdjvBf3dJ1BzLerASFiQ

GET http://localhost:3000/user/refresh?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NDQ1ODM3MSwiZXhwIjoxNzQ1MDYzMTcxfQ.sl0tdH1MIO1HPq85hCvADPDfQPBi7dsEfbDp2rUV1HY

POST http://localhost:3000/user/admin/update_password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiemhhbmdzYW4iLCJyb2xlcyI6WyLnrqHnkIblkZgiXSwicGVybWlzc2lvbnMiOlt7ImlkIjoxLCJjb2RlIjoiY2NjIiwiZGVzY3JpcHRpb24iOiLorr_pl64gY2NjIOaOpeWPoyJ9LHsiaWQiOjIsImNvZGUiOiJkZGQiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBkZGQg5o6l5Y-jIn1dLCJpYXQiOjE3NDQ0NzM5MjIsImV4cCI6MTc0NDQ3NTcyMn0.ufzn0XyK1T5svP5oU3NOuTfvdjvBf3dJ1BzLerASFiQ

{
  "password": "333333",
  "email": "xx@xx.com",
  "captcha": "12312"
}

GET http://localhost:3000/user/list?pageNo=1

GET http://localhost:3000/user/list?pageNo=1&pageSize=4&nickName=李

POST http://localhost:3000/meeting-room/create
Content-Type: application/json

{
  "name": "海王星",
  "capacity": 10,
  "location": "四层西",
  "equipment": "白板,电视",
  "description": "海王星会议室"
}

PUT http://localhost:3000/meeting-room/update
Content-Type: application/json

{
  "id": 4,
  "name": "海王星2",
  "capacity": 10,
  "location": "四层西",
  "equipment": "白板,电视",
  "description": ""
}

DELETE http://localhost:3000/meeting-room/4

GET http://localhost:3000/booking/list?meetingRoomName=木&username=su

POST http://localhost:3000/booking/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiemhhbmdzYW4iLCJlbWFpbCI6IjM0MzE5NjMyM0BxcS5jb20iLCJyb2xlcyI6WyLnrqHnkIblkZgiXSwicGVybWlzc2lvbnMiOlt7ImlkIjoxLCJjb2RlIjoiY2NjIiwiZGVzY3JpcHRpb24iOiLorr_pl64gY2NjIOaOpeWPoyJ9LHsiaWQiOjIsImNvZGUiOiJkZGQiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBkZGQg5o6l5Y-jIn1dLCJpYXQiOjE3NDQ4NzMwODEsImV4cCI6MTc0NDg3NDg4MX0.DvtJ3yBcPM5CRwbJeIWsJLCilJ02hnOFuiOs8yUM3jU

{
    "meetingRoomId": 3,
    "startTime": 1703986859333,
    "endTime": 1703987859333
}

POST http://localhost:3000/booking/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiemhhbmdzYW4iLCJlbWFpbCI6IjM0MzE5NjMyM0BxcS5jb20iLCJyb2xlcyI6WyLnrqHnkIblkZgiXSwicGVybWlzc2lvbnMiOlt7ImlkIjoxLCJjb2RlIjoiY2NjIiwiZGVzY3JpcHRpb24iOiLorr_pl64gY2NjIOaOpeWPoyJ9LHsiaWQiOjIsImNvZGUiOiJkZGQiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBkZGQg5o6l5Y-jIn1dLCJpYXQiOjE3NDQ4NzMwODEsImV4cCI6MTc0NDg3NDg4MX0.DvtJ3yBcPM5CRwbJeIWsJLCilJ02hnOFuiOs8yUM3jU

{
    "meetingRoomId": 3,
    "startTime": 1703986959333,
    "endTime": 1703986859333
}

GET http://localhost:3000/booking/apply/1

GET http://localhost:3000/booking/reject/2

GET http://localhost:3000/booking/unbind/3

GET http://localhost:3000/booking/urge/2

GET http://localhost:3000/statistic/userBookingCount?startTime=2023-1-1&endTime=2025-7-1

GET http://localhost:3000/statistic/meetingRoomUsedCount?startTime=2023-1-1&endTime=2025-7-1
